AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  Notes:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Events:
          create:
            handler: handler.create # point to exported create function in handler.js
            events:
              - http:
                  path: notes # path will be domain.name.com/dev/notes
                  method: post
                  cors: true
            getOne:
              handler: handler.getOne
              events:
                - http:
                    path: notes/{id} # path will be domain.name.com/dev/notes/1
                    method: get
                    cors: true
